### ISSUE TITLE
Improvement to make dreamjs working with karma + PhantomJS + webpack

### ISSUE THREAD

**Issue by bfaf** [adleroliveira/dreamjs#21]
Hi,

I really want to use dreamjs in my project in order to generate data for testing purposes. However I have this nasty error:
>karma start

[2017-02-20 13:31:00.267] [INFO] karma - Karma v1.3.0 server started at http://l
ocalhost:9876/
[2017-02-20 13:31:00.270] [INFO] launcher - Launching browser PhantomJS with unl
imited concurrency
[2017-02-20 13:31:00.274] [INFO] launcher - Starting browser PhantomJS
[2017-02-20 13:31:02.664] [INFO] PhantomJS 2.1.1 (Windows 7 0.0.0) - Connected o
n socket /#vnb5GX37u5VGf7QKAAAA with id 91341862
PhantomJS 2.1.1 (Windows 7 0.0.0) ERROR
  **SyntaxError: Cannot declare a parameter named 'input'  in strict mode**
  at src/test/js/test-index.js:171070

I was able to fix this error by making 2 changes in dream.js and update the name of variable wherever is used in code:

Line 93:  `self.input = function input(input) {   --> self.input = function input(myinput) {`
Line 190:  `self.schema = function schema(schema) { --> self.schema = function schema(myschema) {`

Please if you have time make this change for next release.

**Comment by adleroliveira** [comment]
Hello,

I appreciate your feed feedback. I will take a look in your suggestion for the next release.
In any case, it would be much faster if you could create a pull request with the fix and if all test passes I will just merge it and you would be a contributor to the project.

Best regards,
Adler

**Comment by bfaf** [comment]
I've created pull request :)

**Comment by adleroliveira** [comment]
Thanks for your contribution. I will update the version on NPM.
Cheers,

**Comment by bfaf** [comment]
Thank you for merging it that fast :)

**Comment by adleroliveira** [comment]
Its updated on NPM. Thanks.
