### ISSUE TITLE
Can you update dreamjs with latest chance version!

### ISSUE THREAD

**Issue by zeuzere** [adleroliveira/dreamjs#26]
Hi! i love dreamjs...
Can you udpate to the latest **_chance_** release...

They are new type  like  'company'
if we use  : `dream.schema('workspace', {
  name: 'company'
});`
its not working
So for now, i have updated **_chance_** to the latest version and use your custom type
`dream.customType('company', () => chance.company());`
to make it work

Hope you can update!
Thx
Yves L.

**Comment by adleroliveira** [comment]
Hello @zeuzere thanks for taking interest in the library. May I recommend for you to submit a pull request with this change so I can approve and then updated it on NPM?

Thanks.
