### ISSUE TITLE
why promise?

### ISSUE THREAD

**Issue by YikaJ** [adleroliveira/dreamjs#8]
It seems all dreamjs api is not async, how dreamjs use promises in future?

**Comment by adleroliveira** [comment]
In the new version of the DreamJS (that should be released in the next couple weeks) if you use it with a callback to return your data, it should be possible to resolve the custom types assynchronously. This is already developed and I'm just finishing writing the unit tests for the new features.

Let me know if you have interest in testing beforehand. I could create a different branch to allow people to test it.

Cheers

**Comment by YikaJ** [comment]
Hey buddy, github is an open source community!
I would like to write some tests when I am free ~
